(function(){var a=window;try{do if(a=a.parent,a.QZONE&&a.QZONE.FrontPage&&a.g_iUin)break;while(a!=top)}catch(b){}"undefined"==typeof siDomain&&(siDomain=a.siDomain||"qzonestyle.gtimg.cn");g_V=a.g_V||{};g_V.jq=g_V.jq||"1.9.1";g_V.req=g_V.req||"0.0.9"})();
seajs.config({charset:"utf-8",timeout:3E5,debug:0,paths:{v8:"http://"+siDomain+"/qzone/v8","photo.v7":"http://"+siDomain+"/qzone/photo/v7/js",cssBase:"http://"+siDomain,app:"http://"+siDomain+"/qzone/app","mall.v8":"http://"+siDomain+"/qzone/mall/v8"},alias:{jquery:"http://"+siDomain+"/ac/lib/jquery/jquery-"+g_V.jq,"migrate-plugin":"v8/engine/migrate-plugin.js","interface":"v8/core/interface_mini.js",app_engine:"v8/core/app_engine"+(window.g_diffModules&&g_diffModules.engine?g_diffModules.engine:
"")+".js?max_age=72000",changelog_data:"http://"+siDomain+"/qzone/v6/v6_config/changelog_data.js","console-plus":"v8/engine/console-plus/console-plus.js",embeded:"/applib/embeded.js",request:"v8/engine/request/request_"+g_V.req,"app/v8/config/1.0":"http://"+(siDomain||"qzonestyle.gtimg.cn")+"/c/=/qzone/app/v8/config/(.js,_.js,a.js,b.js,c.js,d.js,e.js,f.js,).js"},map:[[/^.+\/lib\/jquery\.js$/,"http://"+siDomain+"/ac/lib/jquery/jquery-"+g_V.jq+".js"]],comboSyntax:["c/=",","],comboIncludes:/\/qzone\/v8/,
comboExcludes:/jquery|app_engine|music|qzone\/v8\/index\/msgboard/,preload:window.isIframe?["jquery","migrate-plugin","console-plus","request"]:"jquery migrate-plugin interface console-plus app_engine request".split(" ")});
/*  |xGv00|023880a0af574aa05ec730af991df754 */
(function(seajs){if(!seajs.Module){return;}
var Module=seajs.Module,FETCHING=Module.STATUS.FETCHING,data=seajs.data||seajs.config.data,comboHash=data.comboHash={},comboVer=data.comboVer||'',maxageHash={'/qzone/v8/core/interface_mini.js':g_V&&g_V.fp||'7200','/qzone/v8/ic/tab_menu.js':g_V&&g_V.ic||'7200','/qzone/v8/ic/feedsglobal.js':g_V&&g_V.ic||'7200'},comboMaxLength=2000,comboExcludes;seajs.config.data=data;seajs.on("load",setComboHash);seajs.on("fetch",setRequestUri);function setComboHash(uris){if(location.search.indexOf('concat_debug_off')!=-1){QZFL.cookie.set('concat_debug',0,'qzone.qq.com','/',1);}
if(location.search.indexOf('concat_debug_on')!=-1||QZFL.cookie.get('concat_debug')==1){QZFL.cookie.set('concat_debug',1,'qzone.qq.com','/',24);return true;}
var len=uris.length;if(len<2){return;}
data.comboSyntax&&(comboSyntax=data.comboSyntax);data.comboMaxLength&&(comboMaxLength=data.comboMaxLength);comboExcludes=data.comboExcludes;comboIncludes=data.comboIncludes;var needComboUris=[];for(var i=0;i<len;i++){var uri=uris[i];if(comboHash[uri]){continue;}
var mod=Module.get(uri);if(mod.status<FETCHING&&(!comboIncludes||comboIncludes.test(uri))&&(!comboExcludes||!comboExcludes.test(uri))&&!isExcluded(uri)&&!isComboUri(uri)){needComboUris.push(uri);}}
if(needComboUris.length>1){paths2hash(uris2paths(needComboUris));}}
function setRequestUri(data){data.requestUri=comboHash[data.uri]||data.uri;if(comboVer){data.requestUri+=comboVer;}}
function uris2paths(uris){return meta2paths(uris2meta(uris));}
function uris2meta(uris){var meta={__KEYS:[]};for(var i=0,len=uris.length;i<len;i++){var parts=uris[i].replace("://","__").split("/");var m=meta;for(var j=0,l=parts.length;j<l;j++){var part=parts[j];if(!m[part]){m[part]={__KEYS:[]};m.__KEYS.push(part);}
m=m[part];}}
return meta;}
function meta2paths(meta){var paths=[];var __KEYS=meta.__KEYS;for(var i=0,len=__KEYS.length;i<len;i++){var part=__KEYS[i],root=part,m=meta[part],KEYS=m.__KEYS,arr;if(KEYS.length){arr=meta2arr(m);for(var j=0,l=arr.length;j<l;j++){arr[j]='/'+arr[j];}
paths.push([root.replace("__","://"),arr]);}}
return paths;}
function meta2arr(meta){var arr=[],__KEYS=meta.__KEYS;for(var i=0,len=__KEYS.length;i<len;i++){var key=__KEYS[i];var r=meta2arr(meta[key]);var m=r.length;if(m){for(var j=0;j<m;j++){arr.push(key+"/"+r[j]);}}
else{arr.push(key);}}
return arr;}
function paths2hash(paths){for(var i=0,len=paths.length;i<len;i++){var path=paths[i];var root=path[0]+"/";var group=files2group(path[1]);for(var j=0,m=group.length;j<m;j++){setHash(root,group[j]);}}
return comboHash;}
function setHash(root,files){var comboPath=root+comboSyntax[0]+files.join(comboSyntax[1]);var exceedMax=comboPath.length>comboMaxLength;for(var k in maxageHash){if(maxageHash.hasOwnProperty(k)){if(comboPath.indexOf(k)>-1&&comboPath.indexOf('?max_age=')<0){comboPath+='?max_age='+maxageHash[k];}}}
if(files.length>1&&exceedMax){var parts=splitFiles(files,comboMaxLength-(root+comboSyntax[0]).length);setHash(root,parts[0]);setHash(root,parts[1]);}
else{if(exceedMax){throw new Error("The combo url is too long: "+comboPath);}
for(var i=0,len=files.length;i<len;i++){comboHash[root+files[i].slice(1)]=comboPath;}}}
function splitFiles(files,filesMaxLength){var sep=comboSyntax[1],s=files[0];for(var i=1,len=files.length;i<len;i++){s+=sep+files[i];if(s.length>filesMaxLength){return[files.splice(0,i),files];}}}
function files2group(files){var group=[];var hash={};for(var i=0,len=files.length;i<len;i++){var file=files[i];var ext=getExt(file);if(ext){(hash[ext]||(hash[ext]=[])).push(file);}}
for(var k in hash){if(hash.hasOwnProperty(k)){group.push(hash[k]);}}
return group;}
function getExt(file){var p=file.lastIndexOf(".");return p>=0?file.substring(p):"";}
function isExcluded(uri){if(comboExcludes){return comboExcludes.test?comboExcludes.test(uri):comboExcludes(uri);}}
function isComboUri(uri){var comboSyntax=data.comboSyntax||["??",","],s1=comboSyntax[0],s2=comboSyntax[1];return s1&&uri.indexOf(s1)>0||s2&&uri.indexOf(s2)>0}})(seajs);/*  |xGv00|0369911efc16a38840ba29ab7e87225b */G_Param.IC_PREPARE_ITME=new Date;
(function(){function b(c,a){return parseInt(c.charAt(15-Math.floor((a-1)/4)),16)>>(a-1)%4&1}function d(){k=0;try{m(1000100,{bid:QZAPP.Monitor.bid,rc:l.join("")},{reportRate:QZAPP.Monitor.reportRate})}catch(c){console.log("[ERROR] exception in  _reportQueuedException",c)}finally{l=[]}}function e(c,a,f){try{if(!c)return!0;var b,q=g_iLoginUin;"object"==typeof c&&(b=c,c=b.message,a=b.filename,f=b.lineno);var d=["[qq]"+q,"[msg]"+c,"[ua]"+window.navigator.userAgent,"[line]"+f,QZAPP.Monitor.getStack(),"[file]"+
a].join("\n");if(localStorage)if(localStorage.record_bug_message){var e=JSON.parse(localStorage.record_bug_message);10==e.length&&(e=e.slice(1));e.push(d);localStorage.record_bug_message=JSON.stringify(e)}else localStorage.record_bug_message=JSON.stringify([d]);if(p&&!p.test(a))return;if(72===window.g_iLoginUin%100||h)QZAPP.Monitor.reportException(d),console.log("[\u4e0a\u62a5\u9519\u8bef]",d)}catch(k){console.log("[ERROR] exception in  _errorOccured",k)}return!0}var h=function(c,a,f){f=f||1;var d=
typeof a,e,n={};if("object"==d){for(e in a)n[e]=b(c,a[e]);return n}if("number"==d){n="";e=a;for(a+=f||1;e<a;e++)n=b(c,e)+n;return parseInt(n,2)}return-1}(g_LoginBitmap,58,1),l=[],k,p;QZAPP=window.QZAPP||{};QZAPP.Monitor={};QZAPP.Monitor.bid=100001;QZAPP.Monitor.reportRate=100;QZAPP.Monitor.version="";window.console||(window.console={log:function(){},print:function(){},dir:function(){}});var m=function(c,a,f){setTimeout(function(){m.send(c,a,f)},0)};m.send=function(c,a,f){var b=m.config,e=b.defaultParams,
d=[],k=!1;c=c||e.dataId;f=f||e;k=f.method&&"post"==f.method?!0:!1;if("object"==typeof a){for(var h in a)a[h].length&&1024<a[h].length&&(a[h]=a[h].substring(0,1024));"number"!=typeof f.reportRate&&(f.reportRate=1);f.reportRate=Math.round(Math.max(f.reportRate,1));1<f.reportRate&&1<Math.random()*f.reportRate||(k&&QZFL.FormSender?(a.dataId=c,a.sds=Math.random(),c=new QZFL.FormSender(b.webServerInterfaceURL,"post",a,"UTF-8"),c.send()):(a=m.genHttpParamString(a),d.push(b.webServerInterfaceURL,"?"),d.push("dataId=",
c),d.push("&",a,"&"),d.push("ted=",Math.random()),QZFL.pingSender(d.join(""))))}};m.config={webServerInterfaceURL:"http://s.isdspeed.qq.com/cgi-bin/s.fcg",defaultParams:{dataId:1,reportRate:1,method:"get"}};m.genHttpParamString=function(c){var a=[],f;for(f in c)a.push(f+"="+window.encodeURIComponent(c[f]));return a.join("&")};QZAPP.Monitor.setReportID=function(c){c?QZAPP.Monitor.bid=c||100001:console.log("QZAPP.Monitor.setReportID param error bid is null")};QZAPP.Monitor.setReportRate=function(c){c?
QZAPP.Monitor.reportRate=c||100:console.log("QZAPP.Monitor.setReportRate  param error : rate  is null")};QZAPP.Monitor.setConfig=function(c){c||(c={});c.bid&&(QZAPP.Monitor.bid=c.bid);c.rate&&(QZAPP.Monitor.reportRate=c.rate);c.ver&&(QZAPP.Monitor.version=ver);c.reportPattern&&(p=c.reportPattern)};QZAPP.Monitor.setVersion=function(c){c||console.log("QZAPP.Monitor.setReportRate param error : ver is null");QZAPP.Monitor.version=c};QZAPP.Monitor.reportException=function(c,a){l.push((QZAPP.Monitor.version||
"")+": "+c);a?d():k||(k=setTimeout(d,1E3))};QZAPP.Monitor.getStack=function(){var c=[],a=0,f=arguments.callee.caller;f.caller&&(f=f.caller);for(;10>a&&f;){a++;try{c.push(f.toString().replace(/function/g,"FN").substring(0,100)),f=f.caller}catch(b){break}}return c.join("\n")};window.attachEvent?window.attachEvent("onerror",e):window.addEventListener&&window.addEventListener("error",e,!1);QZAPP.Monitor.setReportID(109001);QZAPP.Monitor.setReportRate(1);QZAPP.Monitor.setConfig({reportPattern:/migrate\-plugin|tab_friend_feed|namecard/})})();
(function(){var b=g_Data.feedsPart1&&g_Data.feedsPart1.main,d="friend"==g_ic_fpfeedsType?0:1,e,h=G_Param.qz_referrer,l={qqtips:1,qqgroup:5,special:7},k={0:"friend",1:"me",7:"care"};g_Data.feedsPart1&&g_Data.feedsPart1.main?(0<b.replyHostFeeds_new_cnt-0?(e="host",d=1):0<b.friendFeeds_new_cnt-0&&(e="friend",d=0),l[h]&&(d=l[h]),G_Param.feeds=e,G_Param.scope=d,G_Param.defaultCgiFeedsType=e,G_Param.friendFeedPage=0,G_Param.PageDom=[],G_Param.view=2==b.icView?1:b.icView,G_Param.icPreFile="v8/ic/tab_"+k[d]+
"_feed",setTimeout(function(){window.TCISD&&TCISD.pv&&TCISD.pv("8.qzone.qq.com","tab_"+k[d]+"_direct_pv")},5E3)):G_Param.feeds="friend"})();
seajs.use(["v8/engine/cpu","v8/ic/qm","v8/ic/tab_menu","v8/ic/feeds","v8/toolbar/core",G_Param.icPreFile],function(b,d,e,h,l,k){G_Param.IC_START_ITME=new Date;b.TurnOff.FastLoad=!0;(window.cpujs=b)&&b.bootstrap();var p={_get:function(f,a,c){var b=typeof a,e,d={};if("object"==b){for(e in a)d[e]=p._getBit(f,a[e]);return d}if("number"==b){d="";e=a;for(a+=c||1;e<a;e++)d=p._getBit(f,e)+d;return parseInt(d,2)}return INVALID_PARAM},_getBit:function(a,c){return a?parseInt(a.charAt(15-Math.floor((c-1)/4)),
16)>>(c-1)%4&1:0}};if(g_app_identifier)1!={216:1,weibo:1}[g_app_identifier+""]&&b.fastLoad(QZONE.FrontPage.toApp(location.href));else{var m={};(location.search+location.hash||"").replace(/([^?=&#]+)=([^?&#]*)/gi,function(a,c,b){m[c]=decodeURIComponent(b||"")});var c=window.g_Bitmap_3rd||"0000000000000000";1==window.g_isOFP&&p._get(c,2)&&"toolbar"!=m.via&&QZONE.FrontPage.toApp("appstore?via=QZ.DERECT.APPCENTER")}b.load([e.bootstrap,k.bootstrap,function(){h&&h.bootstrap()},QZONE.Global.Event.scrollEvent.init,
d.bootstrap,l.bootstrap]);QZONE.FrontPage.isInteractZone()&&seajs.use("http://"+siDomain+"/qzone/biz/vpage/v8/v.js",function(a){a&&a.init()});b.TurnOn.Stat=!0;setTimeout(function(){b.load(function(){QZONE.FrontPage.Performance.init()})},6E3);QZFL.imports("http://"+siDomain+"/qzone/v6/qm/qm_100006.js?max_age=900");setTimeout(function(){b.load(function(){seajs.use(["v8/ic/accessory.js"],function(a){a&&b.load(a.bootstrap)});0==g_PreData.hotbar.ret&&seajs.use("app/qbossHotbar/script/qbossHotbar",function(){QZAPP.qbossHotbar.bootstrap(g_PreData.hotbar)})})},
500);setTimeout(function(){b.load(function(){$j.insertCSSLink("http://"+siDomain+"/aoi/icenter-delay"+g_V.delay+".css?max_age=31536000")});b.load(function(){$j.insertCSSLink("http://"+siDomain+"/aoi/fifa-flags.css?max_age=31536000")})},1E3);window.g_Mode="ofp";setTimeout(function(){b.load(function(){seajs.use("http://"+siDomain+"/qzone/v8/engine/compatible.js")})},600);QZONE.qzEvent&&QZONE.qzEvent.addEventListener("_qz_enterAppStart",function(){G_Param.userScrolling=0});seajs.use(window.g_moreModules||
[],function(){QZONE.shop&&b.load(QZONE.shop.initDressUp)});QZONE.console&&QZONE.console.info&&QZONE.console.info("ofp main end");"1"==$j.cookie.get("guider")&&(seajs.use("http://"+siDomain+"/qzone/v8/v8upgrade/v8guider.js",function(a){a&&a.bootstrap()}),$j.cookie.del("guider"));(function(){var a=checkLogin(),c,b;c=window.g_firstLoginTime;isPopupWelcome=QZONE.FP.noShareDb.get(a+"isPopupWelcome");QZONE.FP.noShareDb.get(a+"hasFocusRzBar");b=QZONE.FP.noShareDb.get(a+"closedRzBarDay")||-1;(new Date).getDate();
parseInt(b);"number"!=typeof c||0!=c||isPopupWelcome||seajs.use("http://"+siDomain+"/qzone/v8/ic/welcome/main.js",function(c){c&&(c.bootstrap(),QZONE.FP.noShareDb.set(a+"isPopupWelcome",1))})})();TCISD&&TCISD.pv("home.qzone.qq.com","v8ic");d=1;-1<navigator.userAgent.indexOf("QQBrowser/7")&&(d=5);-1<navigator.userAgent.indexOf("QQBrowser/7.5")&&(d=8);38==window.g_iLoginUin%100&&(d=13);window.g_hasWelcomeflash&&(d=14);var a=TCISD.createTimeStat("icTimeStat",[7820,109,d]);a.setZero(_s_);1==d&&1E4<window.FIRST_PAGE_FEEDS_TIME2-
window._s_?a.mark(13,window.FIRST_PAGE_FEEDS_TIME2):a.mark(1,window.FIRST_PAGE_FEEDS_TIME2);1==d&&(1E4<window.FIRST_PAGE_FEEDS_TIME-window._s_?a.mark(18,window.FIRST_PAGE_FEEDS_TIME):a.mark(15,window.FIRST_PAGE_FEEDS_TIME),1E4<window.FIRST_PAGE_FEEDS_TIME3-window._s_?a.mark(16,window.FIRST_PAGE_FEEDS_TIME3):a.mark(17,window.FIRST_PAGE_FEEDS_TIME3));a.mark(3,G_Param.IC_START_ITME);a.mark(4,g_T.fwp[4]);a.mark(7,G_Param.IC_PREPARE_ITME);setTimeout(function(){a.mark(6,g_T.fwp[3]);0.1>Math.random()&&a.report();
if(5E3<window.FIRST_PAGE_FEEDS_TIME2-window._s_){seajs.use("v8/core/ceSu",function(a){a.init()});seajs.use("v8/core/timing.js");window.time_cdn_start=new Date;var c=new Image;c.onload=function(){window.time_cdn=new Date;c.onload=null};c.src="http://"+siDomain+"/ac/b.gif?t="+Math.random();window.time_user_start=new Date;var b=new Image;b.onload=function(){window.time_user=new Date;b.onload=null};b.src="http://user.qzone.qq.com/b.gif?t="+Math.random();setTimeout(function(){var a=TCISD.createTimeStat("icTimeStat2",
[7820,109,3]);a.setZero(_s_);window.time_cdn&&5E3>=window.time_cdn-window.time_cdn_start?a.mark(10,window.time_cdn-window.time_cdn_start+_s_):a.mark(11,new Date);window.time_user&&5E3>=window.time_cdn-window.time_cdn_start?a.mark(13,window.time_user-window.time_user_start+_s_):a.mark(14,new Date);a.report()},1E4)}},1E4)});
(function(){var b=document.getElementById("qz_poster_editor_v4_container"),d=function(b){seajs.config({alias:{"app/v8/config/1.0":"http://"+(window.siDomain||"qzonestyle.gtimg.cn")+"/c/=/qzone/app/v8/config/(.js,_.js,a.js,b.js,c.js,d.js,e.js,f.js,).js"}});seajs.use(["migrate-plugin","app/v8/config/1.0"],function(d){d.insertCSSLink("http://"+siDomain+"/aoi/icenter-delay"+g_V.delay+".css?max_age=31536000");seajs.use("app/v8/controls/mood_poster/mood_poster_facade",function(d){d.init("QM_Mood_Poster_Container");
b&&b(d)})})};b&&!b.onfocus&&(-1<location.href.indexOf("moodposter_auto_show_")?d():b.onfocus=function(){b.onfocus=function(){this.focused=!0};d();document.getElementById("QM_Mood_Poster_Inner").className="qz-poster bg qz-poster-active";var e=document.getElementById("moodPosterButton"),h=function(b){b()},l=window.ua&&ua.chrome?function(b){this.actOnInputCompleted=h;this.onInputCompleted=b}:h;b.focused=!0;b.actOnInputCompleted=h;b.onInputCompleted=new Function;b.onkeydown=function(b){this.actOnInputCompleted=
l;switch(QZFL.event.getEvent(b).keyCode){case 13:if(QZFL.event.getEvent(b).ctrlKey)e.onclick()}};b.onkeyup=function(){this.actOnInputCompleted=h;this.onInputCompleted()};b.onblur=function(){this.focused=!1;this.actOnInputCompleted=h;this.onInputCompleted()};e.onclick=function(){this.disabled=!0;this.className+=" btn-post-loading";QZFL.widget&&QZFL.widget.msgbox.show("\u6b63\u4e3a\u4f60\u63d0\u4ea4\u6570\u636e...",6,5E3);e=null}})})();
(function(){var b,d,e,h,l,k,p,m,c,a,f,t,q,n,u,v,w,x;QZFL.event.onDomReady(function(){b=new Date-_s_;d=100*document.images.length;e=10*document.getElementsByTagName("*").length;h=1E3*document.getElementsByTagName("script").length;l=1E3*document.getElementsByTagName("iframe").length;k=1E3*document.getElementsByTagName("link").length;p=1E3*document.styleSheets.length;if(ua.ie)try{for(var a=0,f=0,n=document.styleSheets.length;f<n;f++)a+=document.styleSheets[f].rules.length;m=10*a}catch(q){}c=1E3*QZFL.JsLoader.count});
window.onload=function(){a=new Date-_s_;f=100*document.images.length;t=10*document.getElementsByTagName("*").length;q=1E3*document.getElementsByTagName("script").length;n=1E3*document.getElementsByTagName("iframe").length;u=1E3*document.getElementsByTagName("link").length;v=1E3*document.styleSheets.length;if(ua.ie)try{for(var r=0,s=0,y=document.styleSheets.length;s<y;s++)r+=document.styleSheets[s].rules.length;w=10*r}catch(z){}x=1E3*QZFL.JsLoader.count;var g=[];g.push("http://isdspeed.qq.com/cgi-bin/r.cgi?flag1=175&flag2=388&flag3=1");
g.push("&1=",b);g.push("&2=",d);g.push("&3=",e);g.push("&4=",h);g.push("&5=",l);g.push("&6=",k);g.push("&7=",p);g.push("&8=",m);g.push("&9=",c);g.push("&10=",a);g.push("&11=",f);g.push("&12=",t);g.push("&13=",q);g.push("&14=",n);g.push("&15=",u);g.push("&16=",v);g.push("&17=",w);g.push("&18=",x);g.push("&19=",a-b);g.push("&info=qz_v8_ofp_page_detail_stats");g.push("&grz=",Math.random());setTimeout(function(){QZFL.pingSender&&QZFL.pingSender(g.join(""))},16E3)}})();
(function(){setTimeout(function(){seajs.use("jquery",function(b){var d=function(){seajs.use("v8/ic/em_helper",function(b){b.init("pageContent");QZONE.qzEvent.addEventListener("QZ_ON_NEW_FEEDS_RENDER",function(d,l){b.init("main_feed_container")})});d=b.noop};b('a[href="http://user.qzone.qq.com/'+g_iUin+'#pageContent"]').on("keydown",function(b){9!=b.keyCode&&13!=b.keyCode&&32!=b.keyCode||d()})})},1E3)})();
